In [1]:
import pandas as pd

In [7]:
df=pd.read_csv(r"C:\Users\Sahil\OneDrive\Documents\test.csv")

In [11]:
df.head()

Class Index                                              Title  \
0            3                  Fears for T N pension after talks   
1            4  The Race is On: Second Private Team Sets Launc...   
2            4      Ky. Company Wins Grant to Study Peptides (AP)   
3            4      Prediction Unit Helps Forecast Wildfires (AP)   
4            4        Calif. Aims to Limit Farm-Related Smog (AP)   

                                         Description  
0  Unions representing workers at Turner   Newall...  
1  SPACE.com - TORONTO, Canada -- A second\team o...  
2  AP - A company founded by a chemistry research...  
3  AP - It's barely dawn when Mike Fitzpatrick st...  
4  AP - Southern California's smog-fighting agenc...

In [13]:
df.drop(["Title","Class Index"],axis=1)

Description
0     Unions representing workers at Turner   Newall...
1     SPACE.com - TORONTO, Canada -- A second\team o...
2     AP - A company founded by a chemistry research...
3     AP - It's barely dawn when Mike Fitzpatrick st...
4     AP - Southern California's smog-fighting agenc...
...                                                 ...
7595  Ukrainian presidential candidate Viktor Yushch...
7596  With the supply of attractive pitching options...
7597  Like Roger Clemens did almost exactly eight ye...
7598  SINGAPORE : Doctors in the United States have ...
7599  EBay plans to buy the apartment and home renta...

[7600 rows x 1 columns]

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')
x=cv.fit_transform(df['Description'])

In [17]:
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 132190 stored elements and shape (7600, 10529)>

In [18]:
from sklearn.decomposition import LatentDirichletAllocation

In [19]:
LDA = LatentDirichletAllocation(n_components=4,random_state=42)
LDA.fit(x)

LatentDirichletAllocation(n_components=4, random_state=42)

In [20]:
import random

In [21]:
for i in range(20):
  y= random.randint(0,10529)
  print(cv.get_feature_names_out()[y])

lawsuit
linda
hyundai
imported
23
threw
armonk
mighty
opel
lambeau
years
ipod
optimistic
notebooks
shortly
clubs
moons
stemming
negotiators
confusion


In [22]:
len(LDA.components_)

4

In [23]:
LDA.components_

array([[ 5.2488866 , 16.2088483 ,  0.25002947, ...,  3.24797913,
         0.25683339,  2.24935426],
       [ 0.25001025, 21.07284026,  3.21157201, ...,  0.25028891,
         1.64310475,  0.25001375],
       [ 0.25001167, 17.6260592 ,  0.25233171, ...,  0.25135219,
         3.81701141,  0.25061354],
       [ 0.25109148, 93.09225224,  0.28606681, ...,  0.25037978,
         0.28305044,  0.25001845]], shape=(4, 10529))

In [24]:
len(LDA.components_[0])

10529

In [26]:
first_topic = LDA.components_[0]

In [27]:
first_topic.argsort()

array([2978, 9337,  106, ..., 8353, 4003,  177], shape=(10529,))

In [29]:
first_topic[4544]

np.float64(1.2829326709130222)

In [31]:
first_topic[1343]

np.float64(0.25301434854323734)

In [33]:
first_topic.argsort()[-20:]

array([ 8896, 10477,  2563,  2482,  3713,  8257, 10072,  9601,  8364,
       10412,  5396,  9211,  6377, 10339,  9406,  6344,   699,  8353,
        4003,   177])

In [35]:
top_words = first_topic.argsort()[-20:]

In [36]:
for z in top_words:
  print(cv.get_feature_names_out()[z])

sports
year
day
cup
final
saturday
victory
time
second
world
league
sunday
night
win
team
new
ap
season
game
39


In [38]:
for z,topic in enumerate(LDA.components_):
  print(f'the top4 words for topic {z}')
  print([cv.get_feature_names_out()[a] for a in topic.argsort()[-20:]])
  print('\n')

the top4 words for topic 0
['sports', 'year', 'day', 'cup', 'final', 'saturday', 'victory', 'time', 'second', 'world', 'league', 'sunday', 'night', 'win', 'team', 'new', 'ap', 'season', 'game', '39']


the top4 words for topic 1
['business', 'year', 'technology', 'announced', 'computer', 'service', 'fullquote', 'internet', 'million', 'software', 'com', 'microsoft', 'corp', 'reuters', 'said', 'company', '39', 'new', 'lt', 'gt']


the top4 words for topic 2
['tuesday', 'police', 'election', 'afp', 'state', 'monday', 'prime', 'killed', 'officials', 'bush', 'government', 'minister', 'people', 'iraq', 'ap', 'reuters', '39', 'quot', 'president', 'said']


the top4 words for topic 3
['government', 'international', 'report', 'percent', 'quarter', 'united', 'monday', 'thursday', 'wednesday', 'friday', 'world', 'york', 'tuesday', 'prices', 'year', 'reuters', 'oil', 'new', 'said', '39']




#Attaching discoverd topic labels to orginal Article

In [39]:
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 132190 stored elements and shape (7600, 10529)>

In [40]:
x.shape

(7600, 10529)

In [42]:
len(df)

7600

In [43]:
answer = LDA.transform(x)

In [44]:
answer.shape

(7600, 4)

In [45]:
answer[0]

array([0.36347251, 0.5940195 , 0.02237341, 0.02013458])

In [46]:
answer[0].round(2)

array([0.36, 0.59, 0.02, 0.02])

In [47]:
answer[0].argmax()

np.int64(1)

this mean that our model thinks that the first article belongs to topic#1

#combining with original Data

In [48]:
df.head()

Class Index                                              Title  \
0            3                  Fears for T N pension after talks   
1            4  The Race is On: Second Private Team Sets Launc...   
2            4      Ky. Company Wins Grant to Study Peptides (AP)   
3            4      Prediction Unit Helps Forecast Wildfires (AP)   
4            4        Calif. Aims to Limit Farm-Related Smog (AP)   

                                         Description  
0  Unions representing workers at Turner   Newall...  
1  SPACE.com - TORONTO, Canada -- A second\team o...  
2  AP - A company founded by a chemistry research...  
3  AP - It's barely dawn when Mike Fitzpatrick st...  
4  AP - Southern California's smog-fighting agenc...

In [53]:
p=df.drop(["Title","Class Index"],axis=1)

In [49]:
answer.argmax(axis=1)

array([1, 0, 3, ..., 0, 3, 1], shape=(7600,))

In [54]:
p["Topic"] = answer.argmax(axis=1)

In [56]:
p.head(10)

Description  Topic
0  Unions representing workers at Turner   Newall...      1
1  SPACE.com - TORONTO, Canada -- A second\team o...      0
2  AP - A company founded by a chemistry research...      3
3  AP - It's barely dawn when Mike Fitzpatrick st...      0
4  AP - Southern California's smog-fighting agenc...      2
5  The British Department for Education and Skill...      2
6  \\"Sven Jaschan, self-confessed author of the ...      3
7  \\FOAF/LOAF  and bloom filters have a lot of i...      1
8  Wiltshire Police warns about "phishing" after ...      2
9  In its first two years, the UK's dedicated car...      3